[package]
name = "papers"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.3.0"
sourceview5 = { version = "0.3.0" }
libadwaita = "0.1.0-beta-1"
tectonic = "0.8.0"
tempfile = "3.3.0"

# webkit2gtk5 = "0.1.2"
# webkit2gtk5 = "0.1.2"


