[package]
name = "papers"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.3.0"
sourceview5 = { version = "0.3.0" }
libadwaita = "0.1.0-beta-1"
tempfile = "3.3.0"
nom = "7.1.0"
either = "1.6.1"
anyhow = "^1"
tectonic = "0.8.0"
tectonic_bridge_core = "0.3.0"
# poppler-rs = "0.19.0"

# Poppler is not distributed on the Gnome SDK, therefore it is not being used
# on the flatpak build.
# poppler-rs = { git = "https://gitlab.gnome.org/World/Rust/poppler-rs.git", optional = true }

# webkit2gtk5 = "0.1.2"
# webkit2gtk5 = "0.1.2"


